k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: true
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: true
    showTime: true
  currentContext: ""
  currentCluster: ""
  clusters:
    "":
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/w9/kx0jw92j5wbfrh2v35g7g8fw0000gn/T/k9s-screens-uzubair
